###############################
########## Secrets ############
###############################

wifi_ssid: 'YOUR_WIFI_SSID'
wifi_password: 'YOUR_WIFI_PASSWORD'
ota_password: 'OVER_THE_AIR_PASSWORD' # does not need to match anything
ap_password: 'ACCESS_POINT_PASSWORD'  # to connect to fallback access point
api_encryption_key: 'SEE_BELOW'
# To generate Home Assistant Encryption key:
#
#   python3 -c "import base64, os; print(base64.b64encode(os.urandom(32)).decode())"
#
# or visit this page: https://esphome.io/components/api/
# .. and look for the 'encryption' section which will give you a key on that page.
#
